[package]
name = "plt"
version = "5.4.0"
authors = ["Sergey Kacheev <uo0@ya.ru>"]
edition = "2021"

[dependencies]
clap = "~4.4"
itertools = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.9"
